name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            output: roma
          - target: x86_64-unknown-linux-musl
            output: roma
          - target: x86_64-pc-windows-gnu
            output: roma.exe
    steps:
      - uses: actions/checkout@v4  # 更新到最新版本
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Compile
        run: cargo build --release --target=${{ matrix.target }}
      - name: Pack
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf roma-${{ matrix.target }}.tar.gz ${{ matrix.output }}
          sha256sum roma-${{ matrix.target }}.tar.gz > roma-${{ matrix.target }}.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-${{ matrix.target }}/*

  release-apple:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4  # 更新到最新版本
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Compile
        run: cargo build --release --target=${{ matrix.target }}
      - name: Pack
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release/ -zcf roma-${{ matrix.target }}.tar.gz roma
          shasum -a 256 roma-${{ matrix.target }}.tar.gz > roma-${{ matrix.target }}.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-${{ matrix.target }}/*
